name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*-all.jar # Find the shadow jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
